from pathlib import Path

FILES={'0/U': 'FoamFile\n'
        '{\n'
        '    version     2.0;\n'
        '    format      ascii;\n'
        '    class       volVectorField;\n'
        '    object      U;\n'
        '}\n'
        '\n'
        '\n'
        'dimensions      [0 1 -1 0 0 0 0];\n'
        '\n'
        'internalField   uniform (0 0 0);\n'
        '\n'
        'boundaryField\n'
        '{\n'
        '    inlet\n'
        '    {\n'
        '        type fixedValue;\n'
        '        value nonuniform List<vector>\n'
        '20\n'
        '(\n'
        '(0.14625 0 0)\n'
        '(0.41625 0 0)\n'
        '(0.65625 0 0)\n'
        '(0.86625 0 0)\n'
        '(1.04625 0 0)\n'
        '(1.19625 0 0)\n'
        '(1.31625 0 0)\n'
        '(1.40625 0 0)\n'
        '(1.46625 0 0)\n'
        '(1.49625 0 0)\n'
        '(1.49625 0 0)\n'
        '(1.46625 0 0)\n'
        '(1.40625 0 0)\n'
        '(1.31625 0 0)\n'
        '(1.19625 0 0)\n'
        '(1.04625 0 0)\n'
        '(0.86625 0 0)\n'
        '(0.65625 0 0)\n'
        '(0.41625 0 0)\n'
        '(0.14625 0 0)\n'
        ');\n'
        '    }\n'
        '    outlet\n'
        '    {\n'
        '        type            zeroGradient;\n'
        '    }\n'
        '    lowerWall\n'
        '    {\n'
        '        type            noSlip;\n'
        '    }\n'
        '    upperWall\n'
        '    {\n'
        '        type            noSlip;\n'
        '    }\n'
        '    frontAndBack\n'
        '    {\n'
        '        type            empty;\n'
        '    }\n'
        '}\n',
 '0/p': 'FoamFile\n'
        '{\n'
        '    version     2.0;\n'
        '    format      ascii;\n'
        '    class       volScalarField;\n'
        '    object      p;\n'
        '}\n'
        '\n'
        '\n'
        'dimensions      [0 2 -2 0 0 0 0];\n'
        '\n'
        'internalField   uniform 0;\n'
        '\n'
        'boundaryField\n'
        '{\n'
        '    inlet\n'
        '    {\n'
        '        type            zeroGradient;\n'
        '    }\n'
        '    outlet\n'
        '    {\n'
        '        type            fixedValue;\n'
        '        value           uniform 0;\n'
        '    }\n'
        '    lowerWall\n'
        '    {\n'
        '        type            zeroGradient;\n'
        '    }\n'
        '    upperWall\n'
        '    {\n'
        '        type            zeroGradient;\n'
        '    }\n'
        '    frontAndBack\n'
        '    {\n'
        '        type            empty;\n'
        '    }\n'
        '}\n',
 'constant/transportProperties': 'FoamFile\n'
                                 '{\n'
                                 '    version     2.0;\n'
                                 '    format      ascii;\n'
                                 '    class       dictionary;\n'
                                 '    object      transportProperties;\n'
                                 '}\n'
                                 '\n'
                                 '\n'
                                 '\n'
                                 '\n'
                                 'transportModel  Newtonian;\n'
                                 '\n'
                                 'nu              [0 2 -1 0 0 0 0] 2e-4;\n',
 'constant/turbulenceProperties': 'FoamFile\n'
                                  '{\n'
                                  '    version     2.0;\n'
                                  '    format      ascii;\n'
                                  '    class       dictionary;\n'
                                  '    object      turbulenceProperties;\n'
                                  '}\n'
                                  '\n'
                                  '\n'
                                  'simulationType  laminar;\n',
 'system/blockMeshDict': 'FoamFile\n'
                         '{\n'
                         '    version     2.0;\n'
                         '    format      ascii;\n'
                         '    class       dictionary;\n'
                         '    object      blockMeshDict;\n'
                         '}\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         '\n'
                         'scale   1;\n'
                         '\n'
                         'vertices\n'
                         '(\n'
                         '    (-0.05 0.01 0)      \n'
                         '    ( 0    0.01 0)      \n'
                         '    ( 0    0.02 0)      \n'
                         '    (-0.05 0.02 0)      \n'
                         '    ( 0    0    0)      \n'
                         '    ( 0.30 0    0)      \n'
                         '    ( 0.30 0.02 0)      \n'
                         '    (-0.05 0.01 0.01)   \n'
                         '    ( 0    0.01 0.01)   \n'
                         '    ( 0    0.02 0.01)   \n'
                         '    (-0.05 0.02 0.01)   \n'
                         '    ( 0    0    0.01)   \n'
                         '    ( 0.30 0    0.01)   \n'
                         '    ( 0.30 0.02 0.01)   \n'
                         '    ( 0.30 0.01 0)      \n'
                         '    ( 0.30 0.01 0.01)   \n'
                         ');\n'
                         '\n'
                         'blocks\n'
                         '(\n'
                         '    \n'
                         '    hex (0 1 2 3 7 8 9 10) (25 20 1) simpleGrading (1 1 1)\n'
                         '\n'
                         '    \n'
                         '    \n'
                         '    \n'
                         '    hex (4 5 14 1 11 12 15 8) (140 20 1)\n'
                         '    simpleGrading\n'
                         '    (\n'
                         '        (\n'
                         '            (0.333333 0.714286 1)    \n'
                         '            (0.666667 0.285714 4)    \n'
                         '        )\n'
                         '        ( (1 1 4) )                  \n'
                         '        ( (1 1 1) )\n'
                         '    )\n'
                         '\n'
                         '    \n'
                         '    hex (1 14 6 2 8 15 13 9) (140 20 1)\n'
                         '    simpleGrading\n'
                         '    (\n'
                         '        (\n'
                         '            (0.333333 0.714286 1)\n'
                         '            (0.666667 0.285714 4)\n'
                         '        )\n'
                         '        ( (1 1 1) )\n'
                         '        ( (1 1 1) )\n'
                         '    )\n'
                         ');\n'
                         '\n'
                         'edges\n'
                         '(\n'
                         ');\n'
                         '\n'
                         'boundary\n'
                         '(\n'
                         '    inlet\n'
                         '    {\n'
                         '        type patch;\n'
                         '        faces\n'
                         '        (\n'
                         '            (0 7 10 3)\n'
                         '        );\n'
                         '    }\n'
                         '    outlet\n'
                         '    {\n'
                         '        type patch;\n'
                         '        faces\n'
                         '        (\n'
                         '            (5 14 15 12)\n'
                         '            (14 6 13 15)\n'
                         '        );\n'
                         '    }\n'
                         '    lowerWall\n'
                         '    {\n'
                         '        type wall;\n'
                         '        faces\n'
                         '        (\n'
                         '            (0 1 8 7)       \n'
                         '            (4 11 8 1)      \n'
                         '            (4 5 12 11)     \n'
                         '        );\n'
                         '    }\n'
                         '    upperWall\n'
                         '    {\n'
                         '        type wall;\n'
                         '        faces\n'
                         '        (\n'
                         '            (3 10 9 2)\n'
                         '            (2 9 13 6)\n'
                         '        );\n'
                         '    }\n'
                         '    frontAndBack\n'
                         '    {\n'
                         '        type empty;\n'
                         '        faces\n'
                         '        (\n'
                         '            (0 3 2 1)\n'
                         '            (7 8 9 10)\n'
                         '            (4 1 14 5)\n'
                         '            (11 12 15 8)\n'
                         '            (1 2 6 14)\n'
                         '            (8 15 13 9)\n'
                         '        );\n'
                         '    }\n'
                         ');\n'
                         '\n'
                         'mergePatchPairs\n'
                         '(\n'
                         ');\n',
 'system/controlDict': 'FoamFile\n'
                       '{\n'
                       '    version     2.0;\n'
                       '    format      ascii;\n'
                       '    class       dictionary;\n'
                       '    object      controlDict;\n'
                       '}\n'
                       '\n'
                       '\n'
                       'application     simpleFoam;\n'
                       '\n'
                       'startFrom       startTime;\n'
                       'startTime       0;\n'
                       'stopAt          endTime;\n'
                       'endTime         2000;           \n'
                       'deltaT          1;\n'
                       '\n'
                       'writeControl    timeStep;\n'
                       'writeInterval   100;\n'
                       'purgeWrite      0;\n'
                       '\n'
                       'writeFormat     ascii;\n'
                       'writePrecision  12;\n'
                       'writeCompression off;\n'
                       '\n'
                       'timeFormat      general;\n'
                       'timePrecision   6;\n'
                       '\n'
                       'runTimeModifiable true;\n',
 'system/fvSchemes': 'FoamFile\n'
                     '{\n'
                     '    version     2.0;\n'
                     '    format      ascii;\n'
                     '    class       dictionary;\n'
                     '    object      fvSchemes;\n'
                     '}\n'
                     '\n'
                     '\n'
                     'ddtSchemes\n'
                     '{\n'
                     '    default         steadyState;\n'
                     '}\n'
                     '\n'
                     'gradSchemes\n'
                     '{\n'
                     '    default         Gauss linear;\n'
                     '    grad(U)         cellLimited Gauss linear 1;\n'
                     '}\n'
                     '\n'
                     'divSchemes\n'
                     '{\n'
                     '    default         none;\n'
                     '    div(phi,U)      bounded Gauss linearUpwind grad(U);\n'
                     '    div((nuEff*dev2(T(grad(U))))) Gauss linear;\n'
                     '}\n'
                     '\n'
                     'laplacianSchemes\n'
                     '{\n'
                     '    default         Gauss linear corrected;\n'
                     '}\n'
                     '\n'
                     'interpolationSchemes\n'
                     '{\n'
                     '    default         linear;\n'
                     '}\n'
                     '\n'
                     'snGradSchemes\n'
                     '{\n'
                     '    default         corrected;\n'
                     '}\n',
 'system/fvSolution': 'FoamFile\n'
                      '{\n'
                      '    version     2.0;\n'
                      '    format      ascii;\n'
                      '    class       dictionary;\n'
                      '    object      fvSolution;\n'
                      '}\n'
                      '\n'
                      '\n'
                      'solvers\n'
                      '{\n'
                      '    p\n'
                      '    {\n'
                      '        solver          GAMG;\n'
                      '        tolerance       1e-7;\n'
                      '        relTol          0.05;\n'
                      '        smoother        GaussSeidel;\n'
                      '    }\n'
                      '\n'
                      '    U\n'
                      '    {\n'
                      '        solver          PBiCGStab;\n'
                      '        preconditioner  DILU;\n'
                      '        tolerance       1e-8;\n'
                      '        relTol          0.01;\n'
                      '    }\n'
                      '}\n'
                      '\n'
                      'SIMPLE\n'
                      '{\n'
                      '    nNonOrthogonalCorrectors 0;\n'
                      '\n'
                      '    residualControl\n'
                      '    {\n'
                      '        p               1e-5;\n'
                      '        U               1e-6;\n'
                      '    }\n'
                      '}\n'
                      '\n'
                      'relaxationFactors\n'
                      '{\n'
                      '    fields\n'
                      '    {\n'
                      '        p               0.3;\n'
                      '    }\n'
                      '    equations\n'
                      '    {\n'
                      '        U               0.7;\n'
                      '    }\n'
                      '}\n'}
for name,content in FILES.items():
    path=Path("case")/name
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(content)

p=Path('case/constant/transportProperties');p.write_text(p.read_text().replace('2e-4','3e-4'))
