#!/usr/bin/env python3
"""Generate the frozen analytical reference for the laminar Taylor-Couette case.

Pure Python standard library — no third-party dependencies.

Steady laminar circular Couette flow between concentric cylinders
(inner radius R_i rotating at omega, outer radius R_o stationary) has the
exact analytical tangential-velocity profile

    u_theta(r) = A * r + B / r
    A = -omega * R_i**2 / (R_o**2 - R_i**2)
    B =  omega * R_i**2 * R_o**2 / (R_o**2 - R_i**2)

which satisfies u_theta(R_i) = omega * R_i and u_theta(R_o) = 0 by
construction (asserted numerically below). Note the profile is independent
of viscosity; nu only controls how fast the transient relaxes to it.

Outputs (paths relative to this script):
  couette_profile.csv   radial profile, 21 evenly spaced radii R_i..R_o
  ../held_out/qoi.json  held-out QoI utheta_midgap = u_theta((R_i+R_o)/2)

Both artefacts are regenerated byte-identically by re-running this script,
which is the ONLY sanctioned way to (re)produce them — never hand-edit
numbers into either file.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

# --- Case parameters (must match constant/polyMesh/blockMeshDict, 0/U) ---
R_I = 0.05  # inner cylinder radius [m]
R_O = 0.10  # outer cylinder radius [m]
OMEGA = 1.0  # inner cylinder angular velocity [rad/s]
N_POINTS = 21  # radial stations in the reference profile

# --- Analytical solution ---
DENOM = R_O**2 - R_I**2
A = -OMEGA * R_I**2 / DENOM
B = OMEGA * R_I**2 * R_O**2 / DENOM


def u_theta(r: float) -> float:
    """Exact laminar circular-Couette tangential velocity at radius r."""
    return A * r + B / r


def main() -> None:
    here = Path(__file__).resolve().parent

    # Sanity: boundary conditions must hold to machine precision.
    assert abs(u_theta(R_I) - OMEGA * R_I) < 1e-15, "BC at R_i violated"
    assert abs(u_theta(R_O)) < 1e-15, "BC at R_o violated"

    # Radial profile CSV (r in m, u_theta in m/s, 12 significant digits).
    csv_path = here / "couette_profile.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["r", "u_theta"])
        for i in range(N_POINTS):
            r = R_I + (R_O - R_I) * i / (N_POINTS - 1)
            writer.writerow([f"{r:.10f}", f"{u_theta(r):.12g}"])
    print(f"wrote {csv_path}")

    # Held-out QoI: tangential velocity at the mid-gap radius.
    r_mid = 0.5 * (R_I + R_O)
    qoi_path = here.parent / "held_out" / "qoi.json"
    qoi_path.parent.mkdir(parents=True, exist_ok=True)
    with qoi_path.open("w") as f:
        json.dump({"utheta_midgap": u_theta(r_mid)}, f, indent=2)
        f.write("\n")
    print(f"wrote {qoi_path}: utheta_midgap = {u_theta(r_mid)!r} at r = {r_mid}")


if __name__ == "__main__":
    main()
